web:
  build: .
  command: 'bash -c ''go-docker-heroku'''
  working_dir: /app/user
  environment:
    PORT: 8080
    REDIS_URL: 'redis://redis:6379'
  ports:
    - '8080:8080'
  links:
    - redis
test:
  build: .
  command: 'bash -c ''go test -v'''
  working_dir: /app/user/src/github.com/bluele/go-docker-heroku
  environment:
    PORT: 8080
    REDIS_URL: 'redis://redis:6379'
  ports:
    - '8080:8080'
  links:
    - redis
shell:
  build: .
  command: bash
  working_dir: /app/user
  environment:
    PORT: 8080
  ports:
    - '8080:8080'
  volumes:
    - '.:/app/user'
redis:
  image: redis